% -------------------------------------------------------------------
%  Generated by MATLAB on 27-Jun-2018 09:38:59
%  MATLAB version: 9.4.0.813654 (R2018a)
% -------------------------------------------------------------------
saveVarsMat = load('sfterrain_xyz.mat');

xyz = saveVarsMat.xyz; % <65536x3 double> too many elements

clear saveVarsMat;
